version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      #MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: blogs_em
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./db_data:/var/lib/mysql
